services:
  laravel_php84:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_server_php84
    restart: "no"
    volumes:
      - ./projects:/var/www/projects
      - ./docker/apache/sites:/etc/apache2/sites-available
    expose:
      - "80"
    networks:
      - laravel_network

networks:
  laravel_network:
    external: true